version: '3.8'

services:
  creatifpro-postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - creatifpro-network

  creatifpro-back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: creatifpro_back
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://creatifpro-postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - creatifpro-postgres
    networks:
      - creatifpro-network

  creatifpro-front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: creatifpro_front
    ports:
      - "80:80"
    depends_on:
      - creatifpro-back
    networks:
      - creatifpro-network

volumes:
  postgres_data:

networks:
  creatifpro-network:
