services:
  db:
    image: postgres:17
    container_name: creatif_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - creatif-network
    restart: always

  back:
    build: ./back
    container_name: creatif_back
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - creatif-network
    restart: always

  front:
    build: ./front
    container_name: creatif_front
    depends_on:
      - back
    networks:
      - creatif-network
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - creatif-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    networks:
      - creatif-network
  certbot-renew:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    entrypoint: [ "/bin/sh", "-c" ]
    command: [ "while true; do certbot renew --webroot --webroot-path /var/www/certbot/ --quiet && sleep 12h; done" ]
    networks:
      - creatif-network

volumes:
  postgres_data:

networks:
  creatif-network: