# HTTP -> HTTPS redirect
server {
    listen 80;
    listen [::]:80;

    server_name erp.creatif-pro.com www.erp.creatif-pro.com;
    server_tokens off;

    # LetsEncrypt challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    # Redirect everything else to HTTPS non-www
    location / {
        return 301 https://erp.creatif-pro.com$request_uri;
    }
}

