# HTTP -> HTTPS redirect
server {
    listen 80;
    listen [::]:80;

    server_name erp.creatif-pro.com www.erp.creatif-pro.com;
    server_tokens off;

    # LetsEncrypt challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    # Redirect everything else to HTTPS non-www
    location / {
        return 301 https://erp.creatif-pro.com$request_uri;
    }
}

# Main HTTPS server (non-www)
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name erp.creatif-pro.com;

    ssl_certificate     /etc/letsencrypt/live/erp.creatif-pro.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/erp.creatif-pro.com/privkey.pem;

#    # Proxy to backend service
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://back:8080;
    }
}

# Redirect HTTPS www -> non-www
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name www.erp.creatif-pro.com;

    ssl_certificate     /etc/letsencrypt/live/erp.creatif-pro.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/erp.creatif-pro.com/privkey.pem;

    return 301 https://erp.creatif-pro.com$request_uri;
}