# HTTP -> HTTPS redirect
server {
    listen 80;
    listen [::]:80;

    server_name toukrichtemed.com www.toukrichtemed.com;
    server_tokens off;

    # LetsEncrypt challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
        allow all;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Redirect everything else to HTTPS non-www
    location / {
        return 301 https://toukrichtemed.com$request_uri;
    }
}

server {
    listen 443 default_server ssl http2;
    listen [::]:443 ssl http2;
    server_name toukrichtemed.com;
    ssl_certificate /etc/letsencrypt/live/toukrichtemed.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/toukrichtemed.com/privkey.pem;
    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://back:8080;
   }
}

