spring.application.name=creatifpro

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/creatif-pro}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:creatif-pro}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Actuator Configuration for Health Checks
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized

# logging.level.org.springframework.security=TRACE
