server {
    listen 80;
    server_name erp.creatif-pro.com www.erp.creatif-pro.com;

    location /api/ {
        proxy_pass http://creatif_back:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
